### PR TITLE
feat: search bar

### PR DESCRIPTION
**Pull request by gioboa**

### CODE REVIEW

**Comment by ashishkpaul** [comment]
Great,  Thanks

**Comment by ashishkpaul** [comment]
It would be nice if you could add a menu bar to the top left corner.

Screenshot_2023-11-11_19-43-08

**Comment by ashishkpaul** [comment]
and favourite or wishlist icon beside of cart icon

**Comment by gioboa** [comment]
Can you add two issue for these features pls?

**Pull request merged**
